import { Inject, Injectable } from '@nestjs/common';
import { aEnteroPositivo, aTextoOpcional } from '../../shared/dto/parseo.js';
import { construirPaginacion } from '../../shared/dto/respuesta.dto.js';
import { esEstadoActivo } from '../../shared/enums/estado-activo.enum.js';
import { EstadoRegistro } from '../../shared/enums/estado-registro.enum.js';
import { DomainValidationError, RecursoNoEncontradoError } from '../../shared/errors/domain-validation.error.js';
import { CUENTA_REPOSITORY, type CuentaRepository } from '../../cuentas/domain/repositories/cuenta.repository.js';
import { PROYECTO_REPOSITORY, type ProyectoRepository } from '../domain/repositories/proyecto.repository.js';
const actor = 'sistema'; const texto = (v: unknown, c: string) => { const r = aTextoOpcional(v); if (!r) throw new DomainValidationError(`El campo "${c}" es obligatorio.`, c, 'REQUERIDO'); return r; };
export class RegistrarProyectoDto { cuentaId: number; codigo: string; nombre: string; descripcion?: string; }
export class ActualizarProyectoDto { nombre?: string; descripcion?: string | null; estadoActivo?: string; }
@Injectable() export class RegistrarProyectoUseCase { constructor(@Inject(PROYECTO_REPOSITORY) private readonly proyectos: ProyectoRepository, @Inject(CUENTA_REPOSITORY) private readonly cuentas: CuentaRepository) {} async execute(dto: RegistrarProyectoDto) { const cuentaId = aEnteroPositivo(dto.cuentaId, 0); const cuenta = await this.cuentas.findById(cuentaId); if (!cuenta || cuenta.estadoRegistro !== EstadoRegistro.ACTIVO || cuenta.estadoActivo !== 'ACTIVO') throw new RecursoNoEncontradoError('La cuenta indicada no existe o está inactiva.', 'cuentaId', dto.cuentaId); const codigo = texto(dto.codigo, 'codigo').toUpperCase(); if (await this.proyectos.findByCuentaYCodigo(cuentaId, codigo)) throw new DomainValidationError('Ya existe un proyecto con ese código para la cuenta.', 'codigo', 'DUPLICADO'); return this.proyectos.crear({ cuentaId, codigo, nombre: texto(dto.nombre, 'nombre'), descripcion: aTextoOpcional(dto.descripcion), usuarioCreacion: actor }); } }
@Injectable() export class ListarProyectosUseCase { constructor(@Inject(PROYECTO_REPOSITORY) private readonly proyectos: ProyectoRepository) {} async execute(q: { cuentaId?: string; texto?: string; estadoRegistro?: string; page?: string; pageSize?: string }) { const page = aEnteroPositivo(q.page, 1); const pageSize = Math.min(200, aEnteroPositivo(q.pageSize, 50)); const cuentaId = q.cuentaId === undefined ? undefined : aEnteroPositivo(q.cuentaId, 0); const { datos, total } = await this.proyectos.buscar({ cuentaId: cuentaId || undefined, texto: aTextoOpcional(q.texto) ?? undefined, estadoRegistro: q.estadoRegistro === 'TODOS' ? undefined : EstadoRegistro.ACTIVO, page, pageSize }); return { datos, paginacion: construirPaginacion(page, pageSize, total) }; } }
@Injectable() export class ObtenerProyectoUseCase { constructor(@Inject(PROYECTO_REPOSITORY) private readonly proyectos: ProyectoRepository) {} async execute(id: number) { const proyecto = await this.proyectos.findById(id); if (!proyecto) throw new RecursoNoEncontradoError('El proyecto indicado no existe.', 'proyecto', id); return proyecto; } }
@Injectable() export class ActualizarProyectoUseCase { constructor(@Inject(PROYECTO_REPOSITORY) private readonly proyectos: ProyectoRepository) {} async execute(id: number, dto: ActualizarProyectoDto) { await new ObtenerProyectoUseCase(this.proyectos).execute(id); if (dto.estadoActivo !== undefined && !esEstadoActivo(dto.estadoActivo)) throw new DomainValidationError('El estadoActivo no es válido.', 'estadoActivo', 'INVALIDO'); return this.proyectos.actualizar(id, { nombre: dto.nombre === undefined ? undefined : texto(dto.nombre, 'nombre'), descripcion: dto.descripcion === undefined ? undefined : aTextoOpcional(dto.descripcion), estadoActivo: dto.estadoActivo as never, usuarioModificacion: actor }); } }
@Injectable() export class AnularProyectoUseCase { constructor(@Inject(PROYECTO_REPOSITORY) private readonly proyectos: ProyectoRepository) {} async execute(id: number) { await new ObtenerProyectoUseCase(this.proyectos).execute(id); return this.proyectos.anular(id, actor); } }
